// <auto-generated />
using System;
using Clima.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Clima.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clima.Domain.Entities.DadoClimatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DADO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Chuva1h")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("CHUVA_MM_1H");

                    b.Property<decimal?>("Chuva3h")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("CHUVA_MM_3H");

                    b.Property<string>("Cidade")
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("CIDADE");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_COLETA");

                    b.Property<string>("DescricaoClima")
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("DESCRICAO_CLIMA");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<decimal?>("LatApi")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("LAT_API");

                    b.Property<decimal?>("LonApi")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("LON_API");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("TEMPERATURA");

                    b.Property<decimal?>("Umidade")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("UMIDADE");

                    b.Property<decimal?>("VentoVelocidade")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("VENTO_VEL_KMH");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.ToTable("TB_DADOS_CLIMATICOS", (string)null);
                });

            modelBuilder.Entity("Clima.Domain.Entities.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DISPOSITIVO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("IDENTIFICADOR");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UltimaConexao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("ULTIMA_CONEXAO");

                    b.HasKey("Id");

                    b.ToTable("TB_DISPOSITIVO", (string)null);
                });

            modelBuilder.Entity("Clima.Domain.Entities.DadoClimatico", b =>
                {
                    b.HasOne("Clima.Domain.Entities.Dispositivo", "Dispositivo")
                        .WithMany("DadosClimaticos")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DADOS_DISPOSITIVO");

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("Clima.Domain.Entities.Dispositivo", b =>
                {
                    b.Navigation("DadosClimaticos");
                });
#pragma warning restore 612, 618
        }
    }
}
